# Generated by Django 4.0.4 on 2022-05-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='Category/'),
        ),
    ]
