# Generated by Django 4.0.4 on 2022-05-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(null=True, upload_to='Elements/'),
        ),
    ]
