# Generated by Django 4.0.4 on 2022-06-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0003_element_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartonImg', models.ImageField(null=True, upload_to='ConvertImg/')),
                ('EdgeImg', models.ImageField(null=True, upload_to='ConvertImg/')),
            ],
        ),
    ]
