# Generated by Django 4.0.4 on 2022-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0004_imgconvert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_El', models.ImageField(null=True, upload_to='Elements/')),
                ('val_correct', models.CharField(max_length=50, null=True)),
                ('val_fause1', models.CharField(max_length=50, null=True)),
                ('val_fause2', models.CharField(max_length=50, null=True)),
                ('val_fause3', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
