# Generated by Django 4.0.4 on 2022-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0006_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image_El',
            field=models.ImageField(null=True, upload_to='ElementsQuiz/'),
        ),
    ]
