# Generated by Django 4.0.4 on 2022-06-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0007_alter_quiz_image_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='son',
            field=models.FileField(null=True, upload_to='Sound/'),
        ),
    ]
