# Generated by Django 4.0.4 on 2022-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0008_element_son'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='son',
            field=models.FileField(null=True, upload_to='Sound/'),
        ),
    ]
