# Generated by Django 4.0.4 on 2022-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0009_quiz_son'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='son',
            field=models.FileField(null=True, upload_to='SoundName/'),
        ),
    ]
