# Generated by Django 4.0.4 on 2022-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0010_alter_element_son'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
