# Generated by Django 4.0.4 on 2022-07-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rio', '0011_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
